# Generated by Django 4.0.3 on 2022-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='Alert',
            field=models.CharField(blank=True, choices=[('TR', 'Transfer'), ('WD', 'Withdraw')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='Successful',
            field=models.CharField(blank=True, choices=[('SU', 'SuccessFul'), ('US', 'Unsuccessful')], max_length=300, null=True),
        ),
    ]
