# Generated by Django 4.0.3 on 2022-03-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statement_alert_statement_successful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='Alert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='Successful',
            new_name='successful',
        ),
    ]
