# Generated by Django 4.0.3 on 2022-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_alert_statement_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='description',
            field=models.CharField(max_length=30000),
        ),
    ]
